import type { QuickPresetItem, GroceryItem } from '../types/grocery';

export const POPULAR_PRESETS: QuickPresetItem[] = [
  // Bahan Pokok
  {
    id: 'preset-beras-5kg',
    name: 'Beras Ramos Super (5 kg)',
    category: 'Bahan Pokok',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 75000,
    lastMonthPrice: 72000,
    priority: 'essential',
    emoji: '🍚',
    popularReason: 'Makanan pokok utama 1 bulan kos',
  },
  {
    id: 'preset-minyak-2l',
    name: 'Minyak Goreng Sawit (2 Liter)',
    category: 'Bahan Pokok',
    unit: 'botol',
    defaultQty: 1,
    estimatedPrice: 35000,
    lastMonthPrice: 36000,
    priority: 'essential',
    emoji: '🍳',
    popularReason: 'Stok masak lauk harian',
  },
  {
    id: 'preset-telur-1kg',
    name: 'Telur Ayam Negeri (1 kg)',
    category: 'Bahan Pokok',
    unit: 'kg',
    defaultQty: 1,
    estimatedPrice: 28500,
    lastMonthPrice: 28000,
    priority: 'essential',
    emoji: '🥚',
    popularReason: 'Protein murah & praktis',
  },
  {
    id: 'preset-gula-1kg',
    name: 'Gula Pasir Putih (1 kg)',
    category: 'Bahan Pokok',
    unit: 'bungkus',
    defaultQty: 1,
    estimatedPrice: 17500,
    lastMonthPrice: 17000,
    priority: 'essential',
    emoji: '🧂',
    popularReason: 'Pemanis teh & kopi',
  },
  {
    id: 'preset-terigu-1kg',
    name: 'Tepung Terigu Serbaguna (1 kg)',
    category: 'Bahan Pokok',
    unit: 'bungkus',
    defaultQty: 1,
    estimatedPrice: 12000,
    lastMonthPrice: 12000,
    priority: 'essential',
    emoji: '🌾',
    popularReason: 'Bahan gorengan / adonan',
  },

  // Makanan & Camilan
  {
    id: 'preset-indomie-goreng',
    name: 'Indomie Goreng Spesial',
    category: 'Makanan & Camilan',
    unit: 'pcs',
    defaultQty: 10,
    estimatedPrice: 3100,
    lastMonthPrice: 3000,
    priority: 'essential',
    emoji: '🍜',
    popularReason: 'Penyelamat lapar akhir bulan',
  },
  {
    id: 'preset-sarden-kaleng',
    name: 'Sarden Saus Tomat (155g)',
    category: 'Makanan & Camilan',
    unit: 'kaleng',
    defaultQty: 2,
    estimatedPrice: 11500,
    lastMonthPrice: 11000,
    priority: 'essential',
    emoji: '🥫',
    popularReason: 'Lauk instan awet lama',
  },
  {
    id: 'preset-biskuit-roma',
    name: 'Biskuit Gandum / Kelapa (300g)',
    category: 'Makanan & Camilan',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 11000,
    lastMonthPrice: 10500,
    priority: 'optional',
    emoji: '🍪',
    popularReason: 'Camilan santai ngerjain tugas',
  },
  {
    id: 'preset-keripik-kentang',
    name: 'Keripik Kentang Renyah (68g)',
    category: 'Makanan & Camilan',
    unit: 'bungkus',
    defaultQty: 1,
    estimatedPrice: 12500,
    lastMonthPrice: 12000,
    priority: 'optional',
    emoji: '🍟',
    popularReason: 'Jajan waktu nonton / santai',
  },

  // Bumbu & Dapur
  {
    id: 'preset-kecap-bango',
    name: 'Kecap Manis Refill (520 ml)',
    category: 'Bumbu & Dapur',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 22500,
    lastMonthPrice: 22000,
    priority: 'essential',
    emoji: '🍶',
    popularReason: 'Penyedap rasa nasi & telur',
  },
  {
    id: 'preset-saus-abc',
    name: 'Saus Sambal Ekstra Pedas (275 ml)',
    category: 'Bumbu & Dapur',
    unit: 'botol',
    defaultQty: 1,
    estimatedPrice: 13500,
    lastMonthPrice: 13000,
    priority: 'optional',
    emoji: '🌶️',
    popularReason: 'Cocolan gorengan & mie',
  },
  {
    id: 'preset-bawang-merah',
    name: 'Bawang Merah Segar (250 gram)',
    category: 'Bumbu & Dapur',
    unit: 'gram',
    defaultQty: 250,
    estimatedPrice: 12000,
    lastMonthPrice: 14000,
    priority: 'essential',
    emoji: '🧅',
    popularReason: 'Bumbu dasar tumisan',
  },
  {
    id: 'preset-bawang-putih',
    name: 'Bawang Putih (250 gram)',
    category: 'Bumbu & Dapur',
    unit: 'gram',
    defaultQty: 250,
    estimatedPrice: 11000,
    lastMonthPrice: 11000,
    priority: 'essential',
    emoji: '🧄',
    popularReason: 'Bumbu penyedap wangi',
  },

  // Mandi & Kebersihan
  {
    id: 'preset-sabun-cair',
    name: 'Sabun Mandi Cair Refill (450 ml)',
    category: 'Mandi & Kebersihan',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 21500,
    lastMonthPrice: 23000,
    priority: 'essential',
    emoji: '🧼',
    popularReason: 'Higienis harian',
  },
  {
    id: 'preset-shampoo-160ml',
    name: 'Shampoo Anti Ketombe (160 ml)',
    category: 'Mandi & Kebersihan',
    unit: 'botol',
    defaultQty: 1,
    estimatedPrice: 24000,
    lastMonthPrice: 23500,
    priority: 'essential',
    emoji: '🧴',
    popularReason: 'Perawatan rambut',
  },
  {
    id: 'preset-pasta-gigi',
    name: 'Pasta Gigi Fresh (190 gram)',
    category: 'Mandi & Kebersihan',
    unit: 'pcs',
    defaultQty: 1,
    estimatedPrice: 14500,
    lastMonthPrice: 14000,
    priority: 'essential',
    emoji: '🪥',
    popularReason: 'Kesehatan gigi rutin',
  },
  {
    id: 'preset-deterjen',
    name: 'Deterjen Bubuk Cuci Baju (1.8 kg)',
    category: 'Mandi & Kebersihan',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 29500,
    lastMonthPrice: 31000,
    priority: 'essential',
    emoji: '🧺',
    popularReason: 'Cuci baju hemat anak kos',
  },
  {
    id: 'preset-sunlight',
    name: 'Sabun Cuci Piring Jeruk Nipis (650 ml)',
    category: 'Mandi & Kebersihan',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 15500,
    lastMonthPrice: 15000,
    priority: 'essential',
    emoji: '🍽️',
    popularReason: 'Bersihkan minyak perabot kos',
  },

  // Minuman
  {
    id: 'preset-galon-aqua',
    name: 'Air Mineral Galon Isi Ulang (19L)',
    category: 'Minuman',
    unit: 'botol',
    defaultQty: 1,
    estimatedPrice: 20000,
    lastMonthPrice: 20000,
    priority: 'essential',
    emoji: '🚰',
    popularReason: 'Hidrasi air minum utama kos',
  },
  {
    id: 'preset-kopi-sachet',
    name: 'Kopi Bubuk Sachet (10 pcs)',
    category: 'Minuman',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 14000,
    lastMonthPrice: 13500,
    priority: 'optional',
    emoji: '☕',
    popularReason: 'Booster melek begadang nugas',
  },
  {
    id: 'preset-teh-celup',
    name: 'Teh Celup Asli Melati (25 sachet)',
    category: 'Minuman',
    unit: 'pack',
    defaultQty: 1,
    estimatedPrice: 8500,
    lastMonthPrice: 8000,
    priority: 'essential',
    emoji: '🍵',
    popularReason: 'Minuman hangat pagi & sore',
  },
];

export function convertPresetToGroceryItem(preset: QuickPresetItem): GroceryItem {
  return {
    id: `item-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
    name: preset.name,
    category: preset.category,
    unit: preset.unit,
    quantity: preset.defaultQty,
    unitPrice: preset.estimatedPrice,
    lastMonthPrice: preset.lastMonthPrice ?? null,
    discountType: 'none',
    priority: preset.priority,
    isCheckedInCart: false,
    notes: preset.popularReason || 'Ditambahkan via Katalog Cepat',
    createdAt: new Date().toISOString(),
  };
}
